name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    uses: StarCitizenTools/mediawiki-ci-workflows/.github/workflows/lint.yml@main
    with:
      lint-php: true
      runner: ubuntu-24.04-arm

  analyze-php:
    uses: StarCitizenTools/mediawiki-ci-workflows/.github/workflows/analyze-php.yml@main
    with:
      project-type: extension
      project-name: MultiPurge
      runner: ubuntu-24.04-arm

  test-php:
    uses: StarCitizenTools/mediawiki-ci-workflows/.github/workflows/test-php.yml@main
    with:
      project-type: extension
      project-name: MultiPurge
      runner: ubuntu-24.04-arm
